name: RoinReplay
version: ${project.version}
main: me.jumper251.replay.ReplaySystem
description: AdvancedReplay
website: https://github.com/Jumper251/AdvancedReplay
author: Jumper251, TheMiniLuca
depend: [ProtocolLib]
api-version: 1.19
commands:
  replayAdmin:
    permission: replay.admin
    description: 리플레이 메인 커맨드.

